services:
  tomcat:
    image: tomcat:9.0-jdk11
    container_name: MVCJsp
    ports:
      - "8080:8080"
    volumes:
      - ./target/beer-adviser.war:/usr/local/tomcat/webapps/beer-adviser.war
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped



