services:
  tomcat:
    image: tomcat:9.0-jdk11
    container_name: guestlistAjax
    ports:
      - "8080:8080"
    volumes:
      - ./target/guestlistAjax-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/guestlistAjax.war
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped



