services:
  tomcat:
    image: tomcat:9.0-jdk11
    container_name: Bootloader
    ports:
      - "8080:8080"
    volumes:
      - ./target/bootloader.war:/usr/local/tomcat/webapps/bootloader.war
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped



